[build]
  command = "npm install --platform=linux --arch=x64 sharp && npm install && npx prisma generate"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_ENV = "production"

[functions]
  node_bundler = "nft"
  included_files = ["src/generated/**", "node_modules/.prisma/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true
