[build]
  command = "npm install --platform=linux --arch=x64 sharp && npm install && npx prisma generate"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
